apiVersion: batch/v1
kind: Job
metadata:
  name: landmark-indicative-poly-hex-rechunk-res8
  labels:
    k8s-app: landmark-indicative-poly-hex-rechunk-res8
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  backoffLimit: 0
  podFailurePolicy:
    rules:
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget
  ttlSecondsAfterFinished: 10800
  template:
    metadata:
      labels:
        k8s-app: landmark-indicative-poly-hex-rechunk-res8
    spec:
      priorityClassName: opportunistic
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - 'true'
      restartPolicy: Never
      containers:
      - name: hex-task
        image: ghcr.io/boettiger-lab/datasets:latest
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        - name: AWS_HTTPS
          value: 'false'
        - name: AWS_VIRTUAL_HOSTING
          value: 'FALSE'
        - name: TMPDIR
          value: /tmp
        command:
        - bash
        - -c
        - |-
          set -e
          CHUNK_MAP=(0 197 198)
          CHUNK_ID=${CHUNK_MAP[$JOB_COMPLETION_INDEX]}
          echo "Reprocessing chunk $CHUNK_ID at resolution 8"
          cng-datasets vector --input s3://public-indigenous/landmark/indicative-poly.parquet --output s3://public-indigenous/landmark/indicative-poly/chunks --chunk-id $CHUNK_ID --chunk-size 88 --intermediate-chunk-size 10 --resolution 8 --parent-resolutions 0
        resources:
          requests:
            cpu: '4'
            memory: 32Gi
          limits:
            cpu: '4'
            memory: 32Gi
