apiVersion: batch/v1
kind: Job
metadata: {name: swap-2022-species-distributions-merge, labels: {k8s-app: swap-2022-species-distributions-merge}}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  ttlSecondsAfterFinished: 86400
  template:
    metadata: {labels: {k8s-app: swap-2022-species-distributions-merge}}
    spec:
      priorityClassName: opportunistic
      restartPolicy: Never
      containers:
      - name: merge
        image: ghcr.io/boettiger-lab/datasets:latest
        imagePullPolicy: Always
        env:
        - {name: AWS_ACCESS_KEY_ID, valueFrom: {secretKeyRef: {name: aws, key: AWS_ACCESS_KEY_ID}}}
        - {name: AWS_SECRET_ACCESS_KEY, valueFrom: {secretKeyRef: {name: aws, key: AWS_SECRET_ACCESS_KEY}}}
        - {name: AWS_S3_ENDPOINT, value: rook-ceph-rgw-nautiluss3.rook}
        - {name: AWS_HTTPS, value: 'false'}
        - {name: AWS_VIRTUAL_HOSTING, value: 'FALSE'}
        volumeMounts:
        - {name: script, mountPath: /opt/scripts, readOnly: true}
        command: [bash, -c, "set -euo pipefail; python3 /opt/scripts/mixres.py merge 's3://public-nevada/swap-2022/species-distributions/hex8/h0=*/data_0.parquet' 's3://public-nevada/swap-2022/species-distributions/hex10/h0=*/data_0.parquet' s3://public-nevada/swap-2022/species-distributions-small.parquet s3://public-nevada/swap-2022/species-distributions/hex"]
        resources: {requests: {cpu: '4', memory: 32Gi}, limits: {cpu: '4', memory: 32Gi}}
      volumes:
      - {name: script, configMap: {name: nvmo-scripts}}
