apiVersion: batch/v1
kind: Job
metadata:
  name: ics-209-plus-1999-2020-wf-incidents-hex
  labels:
    k8s-app: ics-209-plus-1999-2020-wf-incidents-hex
spec:
  completions: 35
  parallelism: 35
  completionMode: Indexed
  backoffLimitPerIndex: 2
  maxFailedIndexes: 3
  podFailurePolicy:
    rules:
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        k8s-app: ics-209-plus-1999-2020-wf-incidents-hex
    spec:
      restartPolicy: Never
      containers:
      - name: hex-task
        image: ghcr.io/boettiger-lab/datasets:latest
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        - name: AWS_HTTPS
          value: 'false'
        - name: AWS_VIRTUAL_HOSTING
          value: 'FALSE'
        - name: TMPDIR
          value: /tmp
        - name: BUCKET
          value: public-fire
        - name: DATASET
          value: ics-209-plus-1999-2020-wf-incidents
        command:
        - bash
        - -c
        - |-
          set -e
          cng-datasets vector --input s3://public-fire/ics-209-plus-1999-2020/wf-incidents.parquet --output s3://public-fire/ics-209-plus-1999-2020/wf-incidents/chunks --chunk-id ${JOB_COMPLETION_INDEX} --chunk-size 1000 --intermediate-chunk-size 10 --resolution 10 --parent-resolutions 9,8,0
        resources:
          requests:
            cpu: '4'
            memory: 8Gi
            ephemeral-storage: 10Gi
          limits:
            cpu: '4'
            memory: 8Gi
            ephemeral-storage: 10Gi
      priorityClassName: opportunistic
