apiVersion: batch/v1
kind: Job
metadata:
  name: tran-cost-extensification-bmps-rainfed-hex
  labels:
    k8s-app: tran-cost-extensification-bmps-rainfed-hex
spec:
  completions: 122
  parallelism: 50
  completionMode: Indexed
  backoffLimitPerIndex: 2
  maxFailedIndexes: 10
  podFailurePolicy:
    rules:
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget
  ttlSecondsAfterFinished: 10800
  template:
    metadata:
      labels:
        k8s-app: tran-cost-extensification-bmps-rainfed-hex
    spec:
      restartPolicy: Never
      containers:
      - name: hex-task
        image: ghcr.io/boettiger-lab/datasets:latest
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        - name: AWS_HTTPS
          value: 'false'
        - name: AWS_VIRTUAL_HOSTING
          value: 'FALSE'
        - name: GDAL_DATA
          value: /usr/share/gdal
        - name: PYTHONPATH
          value: /usr/lib/python3/dist-packages
        - name: BUCKET
          value: public-nci-frontiers
        volumeMounts:
        - name: rclone-config
          mountPath: /root/.config/rclone
          readOnly: true
        command:
        - bash
        - -c
        - 'set -e


          cng-datasets raster --input "s3://public-nci-frontiers/raw/inputs/transition_costs/tran_cost_extensification_bmps_rainfed.tif"
          --output-parquet s3://public-nci-frontiers/tran-cost-extensification-bmps-rainfed/hex/ --h0-index
          ${JOB_COMPLETION_INDEX} --resolution 8 --parent-resolutions 7,6,5,0 --value-column
          tcost_ext_bmps_rainfed_usd --hex-resampling sum'
        resources:
          requests:
            cpu: '4'
            memory: 64Gi
            ephemeral-storage: 45Gi
          limits:
            cpu: '4'
            memory: 64Gi
            ephemeral-storage: 45Gi
      volumes:
      - name: rclone-config
        secret:
          secretName: rclone-config
      priorityClassName: opportunistic
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - hpc-nrp-g1.nmsu.edu
                - service-02.nrp.mghpcc.org
      activeDeadlineSeconds: 1200
