apiVersion: batch/v1
kind: Job
metadata:
  name: gye-parcels-repartition
  labels:
    k8s-app: gye-parcels-repartition
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 10800
  template:
    metadata:
      labels:
        k8s-app: gye-parcels-repartition
    spec:
      restartPolicy: Never
      containers:
      - name: repartition-task
        image: ghcr.io/boettiger-lab/datasets:latest
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: private-wyoming-rw
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: private-wyoming-rw
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_S3_ENDPOINT
          value: minio.carlboettiger.info
        - name: AWS_PUBLIC_ENDPOINT
          value: minio.carlboettiger.info
        - name: AWS_HTTPS
          value: 'true'
        - name: AWS_VIRTUAL_HOSTING
          value: 'FALSE'
        - name: TMPDIR
          value: /tmp
        - name: BUCKET
          value: private-wyoming
        volumeMounts:
        - name: rclone-config
          mountPath: /root/.config/rclone
          readOnly: true
        command:
        - bash
        - -c
        - |
          set -e
          cng-datasets repartition --chunks-dir s3://private-wyoming/gye-parcels/chunks --output-dir s3://private-wyoming/gye-parcels/hex --source-parquet s3://private-wyoming/gye-parcels/gye-parcels.parquet --cleanup --memory-limit 27GiB
        resources:
          requests:
            cpu: '4'
            memory: 32Gi
            ephemeral-storage: 50Gi
          limits:
            cpu: '4'
            memory: 32Gi
            ephemeral-storage: 50Gi
      volumes:
      - name: rclone-config
        secret:
          secretName: rclone-config-private-wyoming-rw
      priorityClassName: opportunistic
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - 'true'
