#!/usr/bin/env bash
# Generate the MinIO backup machinery: per-bucket k8s Jobs that mirror NRP
# public-<bucket> buckets to office MinIO (minio:public-<bucket>), plus ONE
# weekly CronJob (mechanism, static) + a generated scope ConfigMap (policy).
#
# Mirrors catalog/sync/source-coop/gen-source-sync.sh exactly (same
# single-source-of-truth discipline: re-run this generator after editing
# BUCKETS/MODE/EXCLUDES, then re-apply minio-sync-cron-config.yaml; the
# per-bucket jobs and the weekly cron can never drift). Differences from the
# source.coop generator:
#   - dest is minio:public-<bucket> via the scoped `geo-workflow` key
#     (s3:* on public-* + backup-archive only, Deny s3:ListAllMyBuckets)
#   - recovery guards per the hardening plan (geo-agent-ops#21 step 2c):
#       --max-delete 150   circuit-breaker — abort a run that would delete
#                          more than 150 objects at the dest (stops a
#                          canonical-wipe on NRP from propagating to backup)
#       --backup-dir       deleted/overwritten objects MOVE to
#                          minio:backup-archive/public-<bucket>/<runstamp>/
#                          (private bucket, 90-day expiry lifecycle) instead
#                          of being destroyed = rclone-layer recovery window
#   - Phase 2 STAC-href rewrite (#354): MinIO is a public-read, SERVED DR
#     endpoint, so after each sync a host-swap rewrite makes the mirrored STAC
#     fully self-contained (all hrefs incl. root/parent -> minio.carlboettiger.info),
#     navigable with no link back to NRP. See rewrite-stac-hrefs.py in this dir.
#
# SCOPE = the NRP catalog buckets (the former hand-maintained
# sync-public-*.yaml set). `shared-*` is OUT OF SCOPE (other lab projects'
# data; the scoped key cannot write it — see sync-shared-ca30x30-app.yaml,
# kept separate, pending keep-vs-drop).
#
# GLOBAL_EXCLUDES (#374): build intermediates that must NEVER reach the backup.
# */chunks/**      pre-repartition hex chunks (repartition --cleanup removes them
#                  on NRP, but a sync that races the cleanup mirrors the stale
#                  chunks, and then the >150-file delete to remove them trips the
#                  --max-delete circuit-breaker and wedges the bucket forever).
# */hex-staging/** raster re-hex staging prefix, same failure mode.
# Applied to EVERY bucket, through the same exclude plumbing as per-bucket
# EXCLUDES (single-quoted into the per-bucket YAML; space-listed into buckets.txt
# where the cron re-quotes each "$pat" under set -f). NOTE: an exclude only
# prevents FUTURE mirroring — already-mirrored intermediates need a one-off
# higher-max-delete cleanup (see #374).
GLOBAL_EXCLUDES='*/chunks/** */hex-staging/**'
#
# Per-bucket EXCLUDES (below): none yet. gbif carries known cruft (cache/, dated
# snapshots) — add globs there once Carl confirms exact prefixes (MINIO_AUDIT.md).
set -euo pipefail
OUTDIR="$(cd "$(dirname "$0")/../k8s" && pwd)"
ARCHIVE_BUCKET="backup-archive"

# NRP catalog buckets backed up to MinIO (== NRP public-<bucket>).
BUCKETS=(
  barred-owl
  ca30x30 ca-dac calenviroscreen carbon ca-wolves cdfw census cgs connectivity cpad
  data datacenters dem ecoregion epa-water facts fire gbif gfw globio grids hazard high-seas
  human-modification hydrobasins icca im3 inat indigenous iucn kba land-cover
  mappinginequality mobi nci-frontiers ncp overturemaps padus parks population rap rivers
  social-vulnerability swap tpl trails usfws usgs-nhd usgs-wbd usgs-ungulate-migration
  wdpa wetlands wui wyoming
)
# NOTE (#402): public-nevada + public-missouri were CONSOLIDATED into public-swap
# (per-state SWAP buckets retired). Their per-bucket sync YAMLs were git-rm'd.

# Per-bucket sub-path excludes (rclone --exclude patterns, bucket-root-relative).
declare -A EXCLUDES=(
  # dem raw/ is a re-pullable mirror of Copernicus GLO-90 on AWS Open Data
  # (26k small tiles, not a published STAC artifact) — skip from the DR mirror.
  [dem]='raw/**'
)

# Per-bucket rclone verb. Default "sync" (mirror-with-delete; deletions are
# soft — moved to backup-archive). Override to "copy" (additive) for any
# bucket whose MinIO side must keep content that no longer exists on NRP.
declare -A MODE=(
)

# The gentle-egress recipe shared by the one-off jobs and the cron. The office
# link is 1 Gb/s — keep --bwlimit 50M. --max-delete 150 matches the
# source.coop cron (#347): overturemaps' monthly version swap (~122 H0
# partitions + assets) stays under it; a genuine wipe does not.
FLAGS='--transfers 2 --checkers 4 --bwlimit 50M --tpslimit 5 --retries 5 --max-delete 150'

for bucket in "${BUCKETS[@]}"; do
  src="nrp:public-${bucket}"
  dest="minio:public-${bucket}"
  excl=""
  for pat in ${GLOBAL_EXCLUDES} ${EXCLUDES[$bucket]:-}; do excl="${excl} --exclude '${pat}'"; done
  verb="${MODE[$bucket]:-sync}"
  cat > "${OUTDIR}/sync-public-${bucket}.yaml" <<YAML
# GENERATED by catalog/sync/minio/gen-minio-sync.sh — do not edit by hand.
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-public-${bucket}
  namespace: boettiger-lab
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      priorityClassName: opportunistic
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: NotIn
                    values: ["true"]
      containers:
        - name: sync
          image: ghcr.io/boettiger-lab/datasets:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: rclone-config
              mountPath: /root/.config/rclone
              readOnly: true
          command: [bash, -c]
          args:
            - |
              set -euo pipefail
              SRC="${src}"
              DEST="${dest}"
              # Safety: refuse to write anywhere but the intended catalog
              # mirror path (belt-and-braces on top of the scoped key).
              case "\$DEST" in
                "minio:public-"?*) : ;;
                *) echo "REFUSING: dest '\$DEST' is not a minio:public-* path" >&2; exit 1 ;;
              esac
              RUNSTAMP=\$(date -u +%Y-%m-%dT%H%M%SZ)
              # --max-delete 150: circuit-breaker (abort if a run would delete
              # >150 objects). --backup-dir: deletions/overwrites move to the
              # 90-day backup-archive instead of being destroyed.
              RCLONE_FLAGS="${FLAGS} --backup-dir minio:${ARCHIVE_BUCKET}/public-${bucket}/\${RUNSTAMP} --stats 120s -v"
              # DRYRUN=true (env) lists changes without writing. Default: real sync.
              if [ "\${DRYRUN:-false}" = "true" ]; then RCLONE_FLAGS="\$RCLONE_FLAGS --dry-run"; fi
              rclone mkdir "\$DEST"
              echo "${verb^}ing: \$SRC -> \$DEST  (DRYRUN=\${DRYRUN:-false})"
              rclone ${verb} \$RCLONE_FLAGS${excl} "\$SRC" "\$DEST"
              echo "Done: public-${bucket}"
      volumes:
        - name: rclone-config
          secret:
            secretName: rclone-backup
YAML
  echo "wrote sync-public-${bucket}.yaml  [${verb}]${excl:+  (excludes:${excl})}"
done

echo "Generated ${#BUCKETS[@]} per-bucket jobs into ${OUTDIR}"

# ---------------------------------------------------------------------------
# Scheduled weekly backup = ONE CronJob (mechanism) + generated ConfigMap
# (scope). Same split as source-sync: this file is the single source of truth.
# ---------------------------------------------------------------------------
CFG="${OUTDIR}/minio-sync-cron-config.yaml"
{
  cat <<'HEAD'
# GENERATED by catalog/sync/minio/gen-minio-sync.sh — do not edit by hand.
# Scope consumed by the `minio-sync` CronJob: one line per bucket,
#   <bucket> <rclone-verb> [space-separated exclude globs...]
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-sync-scope
  namespace: boettiger-lab
  labels:
    app: minio-sync
data:
  buckets.txt: |
    # <bucket> <verb> [exclude globs...]
HEAD
  for bucket in "${BUCKETS[@]}"; do
    printf '    %s %s %s\n' "${bucket}" "${MODE[$bucket]:-sync}" "${GLOBAL_EXCLUDES} ${EXCLUDES[$bucket]:-}"
  done
} > "${CFG}"
echo "wrote $(basename "${CFG}")  (${#BUCKETS[@]} buckets)"

CRON="${OUTDIR}/minio-sync-cron.yaml"
cat > "${CRON}" <<'YAML'
# GENERATED by catalog/sync/minio/gen-minio-sync.sh — do not edit by hand.
# Weekly off-NRP backup of every catalogued public-* bucket to office MinIO
# (minio:public-<bucket>) via the scoped geo-workflow key. One pod loops the
# `minio-sync-scope` ConfigMap sequentially at 50 MB/s — the same gentle
# recipe as the per-bucket sync-public-<bucket>.yaml jobs. continue-on-error:
# one bad bucket doesn't block the rest, but the Job exits non-zero so the
# failure is visible. Deletions/overwrites are soft: --max-delete 150 aborts
# a mass delete; --backup-dir moves casualties into
# minio:backup-archive/public-<bucket>/<runstamp>/ (90-day expiry).
#   Apply:      kubectl apply -f minio-sync-cron-config.yaml -f minio-sync-cron.yaml
#   Manual run: kubectl -n boettiger-lab create job --from=cronjob/minio-sync minio-sync-manual
#   Dry run:    edit env DRYRUN=true on the manual Job (lists changes, writes nothing)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-sync
  namespace: boettiger-lab
  labels:
    app: minio-sync
spec:
  schedule: "0 8 * * 6"          # Saturdays 08:00 UTC (source-sync runs Sundays)
  timeZone: Etc/UTC
  concurrencyPolicy: Forbid       # never overlap with a still-running weekly backup
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 604800
      template:
        spec:
          priorityClassName: opportunistic
          restartPolicy: Never
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: feature.node.kubernetes.io/pci-10de.present
                        operator: NotIn
                        values: ["true"]
          containers:
            - name: sync
              image: ghcr.io/boettiger-lab/datasets:latest
              imagePullPolicy: Always
              resources:
                requests: {cpu: "2", memory: "4Gi"}
                limits:   {cpu: "2", memory: "4Gi"}
              env:
                - name: DRYRUN
                  value: "false"
              volumeMounts:
                - name: rclone-config
                  mountPath: /root/.config/rclone
                  readOnly: true
                - name: scope
                  mountPath: /config
                  readOnly: true
              command: [bash, -c]
              args:
                - |
                  set -ufo pipefail           # NOT -e: keep going past a failed bucket. -f: no
                                              # globbing, so exclude patterns stay literal.
                  ARCHIVE_BUCKET="backup-archive"
                  RUNSTAMP=$(date -u +%Y-%m-%dT%H%M%SZ)
                  # --max-delete 150: circuit-breaker — aborts a run that would
                  # delete >150 objects at dest, so an emptied/corrupted NRP
                  # source can't propagate a wipe into the backup.
                  BASE_FLAGS="--transfers 2 --checkers 4 --bwlimit 50M --tpslimit 5 --retries 5 --max-delete 150 --stats 300s -v"
                  if [ "${DRYRUN:-false}" = "true" ]; then BASE_FLAGS="$BASE_FLAGS --dry-run"; fi
                  fail=0 ; n=0
                  while read -r bucket verb excludes; do
                    [ -z "${bucket:-}" ] && continue
                    case "$bucket" in \#*) continue ;; esac
                    # Require an explicit verb. A missing column must NOT
                    # silently default to the destructive `sync`.
                    case "${verb:-}" in
                      sync|copy) : ;;
                      *) echo "REFUSING: bucket '$bucket' has invalid/missing verb '${verb:-}' (want sync|copy)" >&2 ; fail=1 ; continue ;;
                    esac
                    SRC="nrp:public-${bucket}"
                    DEST="minio:public-${bucket}"
                    # Safety: refuse to write anywhere but the catalog mirror
                    # path (belt-and-braces on top of the scoped key).
                    case "$DEST" in
                      "minio:public-"?*) : ;;
                      *) echo "REFUSING: '$DEST' is not a minio:public-* path" >&2 ; fail=1 ; continue ;;
                    esac
                    # --backup-dir: deletions/overwrites move to the 90-day
                    # archive instead of being destroyed (recovery window).
                    args=( "$verb" $BASE_FLAGS --backup-dir "minio:${ARCHIVE_BUCKET}/public-${bucket}/${RUNSTAMP}" )
                    for pat in ${excludes:-} ; do args+=( --exclude "$pat" ) ; done
                    args+=( "$SRC" "$DEST" )
                    n=$((n+1))
                    echo "=== [$n] rclone $verb $SRC -> $DEST  (DRYRUN=${DRYRUN:-false}) ==="
                    rclone mkdir "$DEST" || true
                    if rclone "${args[@]}" ; then echo "OK: $bucket" ; else echo "FAILED: $bucket (rc=$?)" >&2 ; fail=1 ; fi
                  done < /config/buckets.txt
                  # Phase 2 (#354): the sync above makes MinIO an exact copy of
                  # NRP, so the mirrored STAC carries NRP hrefs. Re-apply the
                  # host-swap rewrite so MinIO stays a fully self-contained,
                  # navigable DR catalog (all hrefs incl. root/parent point at
                  # minio.carlboettiger.info). Idempotent; fetched from main;
                  # scope comes from the mounted ConfigMap.
                  echo "=== rewriting STAC hrefs on MinIO (phase 2) ==="
                  RW_URL="https://raw.githubusercontent.com/boettiger-lab/data-workflows/main/catalog/sync/minio/rewrite-stac-hrefs.py"
                  if curl -fsSL "$RW_URL" -o /tmp/rewrite-stac-hrefs.py ; then
                    rwflags="" ; [ "${DRYRUN:-false}" = "true" ] && rwflags="--dry-run"
                    SCOPE_FILE=/config/buckets.txt python3 /tmp/rewrite-stac-hrefs.py $rwflags \
                      || { echo "STAC rewrite FAILED" >&2 ; fail=1 ; }
                  else
                    echo "could not fetch STAC rewrite script from $RW_URL" >&2 ; fail=1
                  fi
                  echo "=== minio-sync complete: $n buckets attempted, fail=$fail ==="
                  exit $fail
          volumes:
            - name: rclone-config
              secret:
                secretName: rclone-backup
            - name: scope
              configMap:
                name: minio-sync-scope
YAML
echo "wrote $(basename "${CRON}")"

echo "Generated ${#BUCKETS[@]} per-bucket jobs + weekly CronJob (minio-sync) into ${OUTDIR}"
